DETA_PROJECT_KEY="d0spnkqtx1x_6hWnMaUCaEjJ318NHJYy66xrwBqZHKi6"
HUGGINGFACE_API_TOKEN="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"
REPO_ID="tiiuae/falcon-7b-instruct"
CLIENT_ID="386097294295-cshguegcn7krddrt1mok2srpsqej1d58.apps.googleusercontent.com"
CLIENT_SECRET="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"
REDIRECT_URI="https://querypls.streamlit.app/"
TEMPLATE="Your task is to create SQL query of the following {question}, just SQL query wrap it into '```' and no text"